### ISSUE TITLE
Quais linguagens foram utilizadas pra fazer? foi muito difícil? 

### ISSUE THREAD

**Issue by PedroFnseca** [Buscafe/Frontend#29]
Fiquei com uma leve duvida sobre o assunto

**Comment by Igorcbraz** [comment]
Utilizamos React para criar o nosso projeto junto com suas bibliotecas. Com muito esforço conseguimos fazer !

**Comment by Igorcbraz** [comment]
> Fiquei com uma leve duvida sobre o assunto

Tudo certo agora ?

**Comment by PedroFnseca** [comment]
com certeza!
